services:
  postgres:
    image: postgres:16
    container_name: pg-expense
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=expense_db
    ports:
      - "5432:5432"
